import type { Business, DashboardMetrics, Insight, Lead, Product } from "@/types/domain";

const now = new Date().toISOString();

export const mockBusiness: Business = {
  id: "b1",
  ownerUserId: "u1",
  name: "Loja do João Celulares",
  slug: "loja-do-joao",
  description:
    "Smartphones selecionados, atendimento rápido pelo WhatsApp e opções para diferentes orçamentos.",
  whatsappNumber: "5511999999999",
  instagramHandle: "@lojadojoaocelulares",
  publicUrl: "/loja-do-joao",
  status: "active",
};

export const mockProducts: Product[] = [
  {
    id: "p1",
    businessId: "b1",
    title: "Samsung S20 FE",
    slug: "samsung-s20-fe",
    description: "128GB, 6GB RAM, câmera versátil e desempenho forte para uso diário.",
    price: 1799,
    currency: "BRL",
    stockQuantity: 2,
    condition: "used",
    status: "active",
    brand: "Samsung",
    category: "smartphone",
    attributes: { storage_gb: 128, ram_gb: 6, battery_mah: 4500, camera_mp: 12, network: "4G" },
    searchText: "Samsung S20 FE 128GB 6GB RAM camera bateria 4500mah bom desempenho",
  },
  {
    id: "p2",
    businessId: "b1",
    title: "iPhone 11",
    slug: "iphone-11",
    description: "64GB, ótimo para fotos e vídeos, com experiência iOS fluida.",
    price: 2100,
    currency: "BRL",
    stockQuantity: 1,
    condition: "used",
    status: "active",
    brand: "Apple",
    category: "smartphone",
    attributes: { storage_gb: 64, camera: "dual", screen_size: 6.1, network: "4G" },
    searchText: "iPhone 11 Apple fotos camera videos iOS usado",
  },
  {
    id: "p3",
    businessId: "b1",
    title: "Moto G84",
    slug: "moto-g84",
    description: "256GB, tela pOLED e bom custo-benefício para quem quer economizar.",
    price: 1399,
    currency: "BRL",
    stockQuantity: 0,
    condition: "new",
    status: "out_of_stock",
    brand: "Motorola",
    category: "smartphone",
    attributes: { storage_gb: 256, ram_gb: 8, battery_mah: 5000, camera_mp: 50, network: "5G" },
    searchText: "Moto G84 Motorola 256GB bateria 5000mah camera 50MP barato",
  },
  {
    id: "p4",
    businessId: "b1",
    title: "Galaxy A15",
    slug: "galaxy-a15",
    description: "128GB, bateria duradoura e preço acessível para uso básico.",
    price: 1199,
    currency: "BRL",
    stockQuantity: 5,
    condition: "new",
    status: "active",
    brand: "Samsung",
    category: "smartphone",
    attributes: { storage_gb: 128, ram_gb: 4, battery_mah: 5000, camera_mp: 50, network: "4G" },
    searchText: "Galaxy A15 Samsung barato bateria 5000mah 128GB camera 50MP",
  },
];

export const mockLeads: Lead[] = [
  {
    id: "l1",
    businessId: "b1",
    productId: "p1",
    originalQuery: "quero celular até R$2000 com câmera boa",
    interpretedQuery: {
      intent: "buy_smartphone",
      category: "smartphone",
      maxPrice: 2000,
      minPrice: null,
      priorities: ["camera"],
      preferredBrands: [],
      excludedBrands: [],
      useCase: null,
    },
    leadSource: "store_search",
    status: "new",
    whatsappClicked: true,
    converted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "l2",
    businessId: "b1",
    productId: "p2",
    originalQuery: "iPhone bom para fotos",
    interpretedQuery: {
      intent: "buy_smartphone",
      category: "smartphone",
      maxPrice: null,
      minPrice: null,
      priorities: ["camera"],
      preferredBrands: ["Apple"],
      excludedBrands: [],
      useCase: null,
    },
    leadSource: "whatsapp_click",
    status: "in_progress",
    whatsappClicked: true,
    converted: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "l3",
    businessId: "b1",
    productId: "p3",
    originalQuery: "celular barato com muita memória",
    interpretedQuery: {
      intent: "buy_smartphone",
      category: "smartphone",
      maxPrice: null,
      minPrice: null,
      priorities: ["price", "storage"],
      preferredBrands: [],
      excludedBrands: [],
      useCase: null,
    },
    leadSource: "store_search",
    status: "sold",
    whatsappClicked: true,
    converted: true,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockInsights: Insight[] = [
  {
    id: "i1",
    businessId: "b1",
    type: "demand_gap",
    title: "Clientes querem opções até R$1500",
    description:
      "As buscas por celulares baratos cresceram esta semana, mas poucas opções ativas estão nessa faixa.",
    impactLevel: "high",
    suggestedAction: "Anunciar modelos de entrada e destacar o Galaxy A15.",
    status: "new",
    createdAt: now,
  },
  {
    id: "i2",
    businessId: "b1",
    type: "conversion_alert",
    title: "S20 FE tem muitos cliques",
    description: "O produto aparece bem nas recomendações, mas ainda tem poucas vendas registradas.",
    impactLevel: "medium",
    suggestedAction: "Verificar abordagem no WhatsApp e disponibilidade real.",
    status: "new",
    createdAt: now,
  },
];

export const mockMetrics: DashboardMetrics = {
  visits: 248,
  searches: 118,
  whatsappClicks: 24,
  leads: 32,
  soldLeads: 7,
  leadConversionRate: 22,
  outOfStockProducts: 1,
};
